[phases.setup]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/22.11.tar.gz"
nixpkgsPackages = ["chromium", "fontconfig", "freetype", "nss"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node app.js"